### ISSUE TITLE
SmartReadException: Inconsistent Data when a USB drive is plugged in

### ISSUE THREAD

**Issue by M-Pixel** [rstarkov/BasicSMART#1]
```
Unhandled Exception: BasicSMART.SmartReadException: Inconsistent data [DeviceIndex=2, Serial=0D7F038070C0]
   at BasicSMART.SMART.assert(SmartDriveInfo drv, Boolean assertion)
   at BasicSMART.SMART.GetDrives()
```

**Comment by M-Pixel** [comment]
The assertion, unfortunately, does not log what exactly it's asserting.  It turns out it's failing at `assert(drive, drive.Model == (string) drive2["Model"]);` because (in my case) lhs is "Voyager VEGA" and rhs is "Corsair Voyager VEGA USB Device".

What is the intent behind this assertion, and the other assertions that compare `drive.Model` against several other values?

**Comment by rstarkov** [comment]
Hmm. IIRC the way the two data sources are matched against each other is a bit iffy, so the assertion was there because it worked for all of my 6 HDDs. I suppose it could be removed.
